### ISSUE TITLE
opam

### ISSUE THREAD

**Issue by nickbetteridge** [swuecho/camelsnakekebab#2]
This library would be a very useful addition to the opam packages :)

**Comment by swuecho** [comment]
glad that you find it useful. Di you mind make a pull request? 

or I will go though the process to submit to opam when I am ready to do some ocaml coding.

**Comment by nickbetteridge** [comment]
Ah - I used your code as a reference and wrote a few functions to implement my requirements. Sorry. It would still be a very useful addition to opam, I think.

**Comment by swuecho** [comment]
on opam now. 

https://opam.ocaml.org/packages/camelsnakekebab/
